# Generated by Django 6.0 on 2025-12-11 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
        ('users', '0002_remove_user_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dealer_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='dealers.dealer'),
        ),
    ]
