# Generated by Django 6.0 on 2025-12-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('make', models.CharField(max_length=200)),
                ('fuel_type', models.CharField(choices=[('Electric', 'Electric'), ('Regular', 'Regular'), ('Premium', 'Premium'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid')], max_length=50)),
                ('type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Coupe', 'Coupe'), ('Sports', 'Sports'), ('Compact', 'Compact'), ('Supercar', 'Supercar')], max_length=50)),
                ('capacity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
